# Cloning data from GitHub

In [ ]:
# Clone the ZZSC9020 project repository from GitHub
#!git clone https://github.com/UNSW-ZZSC9020-2023H2/project.git

Cloning into 'project'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 25 (delta 0), reused 2 (delta 0), pack-reused 21
Unpacking objects: 100% (25/25), 121.23 MiB | 11.77 MiB/s, done.
Updating files: 100% (12/12), done.

In [ ]:
# Create a data folder
#!mkdir -p data

In [ ]:
# Joint forecastdemand_nsw files into a single file. 
#!cat project/data/forecastdemand_nsw.csv.zip.part* > data/forecastdemand_nsw.csv.zip

In [ ]:
# Unzip the data files into the data folder
#!unzip data/forecastdemand_nsw.csv.zip -d data
#!unzip project/data/temperature_nsw.csv.zip -d data
#!unzip project/data/totaldemand_nsw.csv.zip -d data

Archive:  data/forecastdemand_nsw.csv.zip
  inflating: data/forecastdemand_nsw.csv
  inflating: data/__MACOSX/._forecastdemand_nsw.csv
Archive:  project/data/temperature_nsw.csv.zip
  inflating: data/temperature_nsw.csv
  inflating: data/__MACOSX/._temperature_nsw.csv
Archive:  project/data/totaldemand_nsw.csv.zip
  inflating: data/totaldemand_nsw.csv
  inflating: data/__MACOSX/._totaldemand_nsw.csv

In [ ]:
# Remove forecastdemand_nsw.csv.zip
#!rm data/forecastdemand_nsw.csv.zip

# Import libraries

In [71]:
import pandas as pd
import numpy as np
from datetime import datetime

# Data preprocessing

In [84]:
# Load the data
totaldemand = pd.read_csv('data/totaldemand_nsw.csv')
temperature = pd.read_csv('data/temperature_nsw.csv')
forecastdemand = pd.read_csv('data/forecastdemand_nsw.csv')

In [85]:
# Check for NaN values
print(f'NaN values in totaldemand= {totaldemand.isna().sum().sum()}')
print(f'NaN values in temperature= {temperature.isna().sum().sum()}')
print(f'NaN values in forecastdemand= {forecastdemand.isna().sum().sum()}')

NaN values in totaldemand= 0
NaN values in temperature= 0
NaN values in forecastdemand= 0

In [86]:
# Check for zero or negative values
print(f'Zero or negative values in totaldemand= {((totaldemand.select_dtypes(include=np.number)<=0).any(axis=1)).sum()}')
print(f'Zero or negative values in temperature= {((temperature.select_dtypes(include=np.number)<=0).any(axis=1)).sum()}')
print(f'Zero or negative values in forecastdemand= {((forecastdemand.select_dtypes(include=np.number)<=0).any(axis=1)).sum()}')

Zero or negative values in totaldemand= 0
Zero or negative values in temperature= 36
Zero or negative values in forecastdemand= 0

In [87]:
# Explore extreme temperature values
temperature.loc[temperature['TEMPERATURE']<=0]

                   DATETIME  LOCATION  TEMPERATURE
4234    2010-03-23 15:00:00   94766.0      -9999.0
6017    2010-04-27 10:00:00   94766.0      -9999.0
6196    2010-05-01 06:00:00   94766.0      -9999.0
9351    2010-06-29 04:30:00   94766.0         -0.2
9353    2010-06-29 05:30:00   94766.0         -0.1
9356    2010-06-29 06:30:00   94766.0         -0.3
9403    2010-06-30 04:30:00   94766.0         -0.3
9404    2010-06-30 05:00:00   94766.0         -0.5
9405    2010-06-30 05:30:00   94766.0         -0.4
10611   2010-07-23 18:30:00   94766.0      -9999.0
18423   2010-12-20 01:30:00   94766.0      -9999.0
18424   2010-12-20 02:00:00   94766.0      -9999.0
18425   2010-12-20 02:30:00   94766.0      -9999.0
18426   2010-12-20 03:00:00   94766.0      -9999.0
18427   2010-12-20 03:30:00   94766.0      -9999.0
18428   2010-12-20 04:00:00   94766.0      -9999.0
18429   2010-12-20 04:30:00   94766.0      -9999.0
18430   2010-12-20 05:00:00   94766.0      -9999.0
18431   2010-12-20 05:30:00   94766.0      -9999.0
18432   2010-12-20 06:00:00   94766.0      -9999.0
18433   2010-12-20 06:30:00   94766.0      -9999.0
18434   2010-12-20 07:00:00   94766.0      -9999.0
18435   2010-12-20 07:30:00   94766.0      -9999.0
18436   2010-12-20 11:30:00   94766.0      -9999.0
18437   2010-12-20 12:00:00   94766.0      -9999.0
167568  2018-07-16 02:30:00   94766.0         -0.5
167569  2018-07-16 03:00:00   94766.0         -0.1
167570  2018-07-16 03:30:00   94766.0         -0.4
167571  2018-07-16 04:00:00   94766.0         -0.4
167572  2018-07-16 04:30:00   94766.0         -0.9
167573  2018-07-16 05:00:00   94766.0         -0.7
167574  2018-07-16 05:30:00   94766.0         -0.7
167575  2018-07-16 06:00:00   94766.0         -1.2
167576  2018-07-16 06:30:00   94766.0         -1.3
167577  2018-07-16 07:00:00   94766.0         -0.6
167578  2018-07-16 07:30:00   94766.0         -0.3

In [95]:
# Remove rows with unreasonable values
temperature = temperature.loc[temperature['TEMPERATURE']!=-9999]

In [96]:
# Convert relevant columns to datetime format
datetime_format = '%Y-%m-%d %H:%M:%S'
totaldemand['DATETIME'] = pd.to_datetime(totaldemand['DATETIME'], format=datetime_format)
temperature['DATETIME'] = pd.to_datetime(temperature['DATETIME'], format=datetime_format)
forecastdemand['DATETIME'] = pd.to_datetime(forecastdemand['DATETIME'], format=datetime_format)
forecastdemand['LASTCHANGED'] = pd.to_datetime(forecastdemand['LASTCHANGED'], format=datetime_format)

In [97]:
# Explore totaldemand data 
print(totaldemand.info())
print(totaldemand.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1323398 entries, 0 to 1323397
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   DATETIME     1323398 non-null  datetime64[ns]
 1   REGIONID     1323398 non-null  object
 2   TOTALDEMAND  1323398 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 30.3+ MB
None
             DATETIME REGIONID  TOTALDEMAND
0 2010-01-01 00:00:00     NSW1      7997.41
1 2010-01-01 00:05:00     NSW1      7946.51
2 2010-01-01 00:10:00     NSW1      7921.55
3 2010-01-01 00:15:00     NSW1      7837.84
4 2010-01-01 00:20:00     NSW1      7781.11

In [98]:
# Explore temperature data
print(temperature.info())
print(temperature.head())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 247627 entries, 0 to 247645
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATETIME     247627 non-null  datetime64[ns]
 1   LOCATION     247627 non-null  float64
 2   TEMPERATURE  247627 non-null  float64
dtypes: datetime64[ns](1), float64(2)
memory usage: 7.6 MB
None
             DATETIME  LOCATION  TEMPERATURE
0 2010-01-01 00:00:00   94766.0         23.1
1 2010-01-01 00:01:00   94766.0         23.1
2 2010-01-01 00:30:00   94766.0         22.9
3 2010-01-01 00:50:00   94766.0         22.7
4 2010-01-01 01:00:00   94766.0         22.6

In [99]:
# Explore forecastdemand data
print(forecastdemand.info())
print(forecastdemand.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11619503 entries, 0 to 11619502
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   DATETIME          datetime64[ns]
 1   REGIONID          object
 2   FORECASTDEMAND    float64
 3   PREDISPATCHSEQNO  int64
 4   PERIODID          int64
 5   LASTCHANGED       datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2), object(1)
memory usage: 531.9+ MB
None
    DATETIME REGIONID  FORECASTDEMAND  PREDISPATCHSEQNO  PERIODID  \
0 2010-01-01     NSW1         7832.04        2009123018        71
1 2010-01-01     NSW1         7832.04        2009123019        70
2 2010-01-01     NSW1         7832.03        2009123020        69
3 2010-01-01     NSW1         7832.03        2009123021        68
4 2010-01-01     NSW1         7830.96        2009123022        67

          LASTCHANGED
0 2009-12-30 12:31:49
1 2009-12-30 13:01:43
2 2009-12-30 13:31:36
3 2009-12-30 14:01:44
4 2009-12-30 14:31:35